[package]
name = "vizia"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A Rust GUI Framework"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[[example]]
name = "button"
path = "examples/controls/button.rs"


[[example]]
name = "slider"
path = "examples/controls/slider.rs"

[[example]]
name = "knob"
path = "examples/controls/knob.rs"

[[example]]
name = "checkbox"
path = "examples/controls/checkbox.rs"

[[example]]
name = "radiobutton"
path = "examples/controls/radiobutton.rs"

[[example]]
name = "zstack"
path = "examples/controls/zstack.rs"

[[example]]
name = "picker"
path = "examples/controls/picker.rs"

[[example]]
name = "popup"
path = "examples/controls/popup.rs"

[[example]]
name = "dropdown"
path = "examples/controls/dropdown.rs"

[[example]]
name = "textbox"
path = "examples/controls/textbox.rs"

[[example]]
name = "list"
path = "examples/lists/list.rs"

[[example]]
name = "selectable_list"
path = "examples/lists/selectable_list.rs"

[[example]]
name = "editable_list"
path = "examples/lists/editable_list.rs"

[[example]]
name = "multiselectable_list"
path = "examples/lists/multiselectable_list.rs"

[[example]]
name = "static_list"
path = "examples/lists/static_list.rs"


[features]
default = ["glutin", "clipboard"]
clipboard = ["vizia_core/clipboard"]
glutin = ["vizia_glutin"]
baseview = ["vizia_baseview"]
meadowlark = ["glutin", "vizia_core/meadowlark"]


[dependencies]
vizia_core = { version = "0.1.0", path = "core"}
vizia_glutin = { version = "0.1.0", path = "glutin", optional = true }
vizia_baseview = { version = "0.1.0", path = "baseview", optional = true }

[dev-dependencies]
english-numbers = "0.3.3"
lazy_static = "1.4.0"

[patch."https://github.com/glowcoil/raw-gl-context"]
raw-gl-context = { git = "https://github.com/prokopyl/raw-gl-context" }
